# this is just a simple test device setup that's used to compile and test the examples

esphome:
    name: balboa-spa-test-esp32
    build_path: .build/balboa_spa_test_esp32
    platformio_options:
      build_flags:
        - "-DARDUINO_USB_CDC_ON_BOOT=1"

esp32:
  board: lolin_s2_mini
  framework: 
    type: arduino
    platform_version: 6.10.0