# this is just a simple test device setup that's used to compile and test the examples

esphome:
    name: balboa-spa-test-esp8266
    build_path: .build/balboa_spa_test_esp8266

esp8266:
  board: esp01_1m
