# this configuration file has all empty custom components set up.
# use 'esphome test_empty.yaml compile' to build. 

external_components:
  - source:
      type: local
      path: components

balboa_spa:
  id: test_spa

switch:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    jet1:
      name: Jet1
    jet2:
      name: Jet2
    light:
      name: Lights

climate:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    name: "Spa Thermostat"
    visual:
      min_temperature: 62 °F    # min: 17
      max_temperature: 105 °F    # max: 30
      temperature_step: 0.5 °F  # min: 0.5

sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    blower:
      name: Blower
    highrange:
      name: High Range
    circulation:
      name: Circulation
    restmode:
      name: Rest Mode
    heatstate:
      name: Heat State
