external_components:
  - source:
      type: local
      path: components

balboa_spa:
  id: test_spa
  spa_temp_scale: F  # Set to match your spa's native configuration (C or F)
  esphome_temp_scale: C  # Set to your preferred units for ESPHome

climate:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    name: "Spa Climate"

switch:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    jet1:
      name: "Jet1"
      icon: "mdi:fan"
    jet2:
      name: "Jet2"
      icon: "mdi:fan"
    jet3:
      name: "Jet3"
      icon: "mdi:fan"
    jet4:
      name: "Jet4"
      icon: "mdi:fan"
    light:
      name: "Lights"
      icon: "mdi:lightbulb"
    blower:
      name: "Blower"
      icon: "mdi:grain"

sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    blower:
      name: "Blower"
    highrange:
      name: "High Range"
    circulation:
      name: "Circulation Pump"
    restmode:
      name: "Rest Mode"
    heatstate:
      name: "Heat State"

binary_sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    blower:
      name: "Blower"
      entity_category: diagnostic
      device_class: power
    highrange:
      name: "High Range"
      entity_category: diagnostic
    circulation:
      name: "Circulation Pump"
      entity_category: diagnostic
      device_class: power
    restmode:
      name: "Rest Mode"
      entity_category: diagnostic
    heatstate:
      name: "Heat State"
      entity_category: diagnostic
      device_class: power
    connected:
      name: "Connected"
      icon: "mdi:lan-connect"
      entity_category: diagnostic