# this configuration file has all empty custom components set up.
# use 'esphome test_empty.yaml compile' to build. 

external_components:
  - source:
      type: local
      path: components

balboa_spa:
  id: test_spa
  spa_temp_scale: F
  esphome_temp_scale: C

switch:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    jet1:
      name: Jet1
    jet2:
      name: Jet2
    jet3:
      name: Jet3
    jet4:
      name: Jet4
    light:
      name: Lights
    light2:
      name: Second Lights
    blower:
      name: Blower

climate:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    name: "Spa Thermostat"
    visual:
      min_temperature: 62 °F    # min: 17
      max_temperature: 105 °F    # max: 30
      temperature_step: 0.5 °F  # min: 0.5

sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    blower:
      name: Blower
    highrange:
      name: High Range
    circulation:
      name: Circulation
    restmode:
      name: Rest Mode
    heatstate:
      name: Heat State

binary_sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    blower:
      name: Blower
    highrange:
      name: High Range
    circulation:
      name: Circulation Pump
    restmode:
      name: Rest Mode
    heatstate:
      name: Heat State
    connected:
      name: Connected

text_sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    spa_time:
      name: "Spa Time"
    filter1_config:
      name: "Filter 1 Config"
    filter2_config:
      name: "Filter 2 Config"

button:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    sync_time:
      name: "Sync Spa Time"

text:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    spa_time:
      name: "Set Spa Time"
      mode: TEXT
    filter1_start_time:
      name: "Set Filter 1 Start Time"
      mode: TEXT
    filter1_duration:
      name: "Set Filter 1 Duration"
      mode: TEXT
    filter2_start_time:
      name: "Set Filter 2 Start Time"  
      mode: TEXT
    filter2_duration:
      name: "Set Filter 2 Duration"
      mode: TEXT
