# this configuration file has all empty custom components set up.
# use 'esphome test_empty.yaml compile' to build. 

external_components:
  - source:
      type: local
      path: components

balboa_spa:
  id: test_spa
  spa_temp_scale: F
  esphome_temp_scale: C

# Example 1: Using switches for simple ON/OFF control (backwards compatible)
switch:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    jet1:
      name: Jet1
      max_toggle_attempts: 5  # Optional: default is 5
    jet2:
      name: Jet2
      discard_updates: 20 # Optional: default is 20
    jet3:
      name: Jet3
    jet4:
      name: Jet4
    light:
      name: Lights
    light2:
      name: Second Lights
    blower:
      name: Blower
    highrange:
      name: Temperature Mode
    filter2:
      name: "Filter 2"

fan:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    jet_1:
      name: "Jet 1 Fan"
      id: jet1_fan
      max_toggle_attempts: 4
    jet_2:
      name: "Jet 2 Fan"
      id: jet2_fan
      discard_updates: 10
    jet_3:
      name: "Jet 3 Fan"
      id: jet3_fan
    jet_4:
      name: "Jet 4 Fan"
      id: jet4_fan
      discard_updates: 5
      max_toggle_attempts: 2

climate:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    name: "Spa Thermostat"
    visual:
      min_temperature: 62 °F    # min: 17
      max_temperature: 105 °F    # max: 30
      temperature_step: 0.5 °F  # min: 0.5

sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    blower:
      name: Blower
    highrange:
      name: High Range
    circulation:
      name: Circulation
    restmode:
      name: Rest Mode
    heatstate:
      name: Heat State
    fault_code:
      name: Fault Code
    fault_total_entries:
      name: Fault Total Entries
    fault_current_entry:
      name: Fault Current Entry
    fault_days_ago:
      name: Fault Days Ago

binary_sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    blower:
      name: Blower
    highrange:
      name: High Range
    circulation:
      name: Circulation Pump
    restmode:
      name: Rest Mode
    heatstate:
      name: Heat State
    connected:
      name: Connected
    filter1_running:
      name: Filter 1 Running
    filter2_running:
      name: Filter 2 Running

text_sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    spa_time:
      name: "Spa Time"
    filter1_config:
      name: "Filter 1 Config"
    filter2_config:
      name: "Filter 2 Config"
    fault_message:
      name: "Fault Message"
    fault_log_time:
      name: "Fault Log Time"
    reminder:
      name: "Reminder"
    component_version:
      name: "Component Version"

button:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    sync_time:
      name: "Sync Spa Time"
    disable_filter2:
      name: "Disable Filter 2"
    request_fault_log:
      name: "Request Fault Log"
    clear_reminder:
      name: "Clear Reminder"

text:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    spa_time:
      name: "Set Spa Time"
      mode: TEXT
    filter1_start_time:
      name: "Set Filter 1 Start Time"
      mode: TEXT
    filter1_duration:
      name: "Set Filter 1 Duration"
      mode: TEXT
    filter2_start_time:
      name: "Set Filter 2 Start Time"  
      mode: TEXT
    filter2_duration:
      name: "Set Filter 2 Duration"
      mode: TEXT
